# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run

name : CI

on : push

jobs: 
  send_mail : 
    runs-on : Ubuntu-latest
    
    steps:
      - name: Send mail
        uses: mosesbalaji/myaction@v2.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Test Email trigger by github actions
          # Required recipients' addresses:
          to: suripa.saha111@gmail.com
          # Required sender full name (address can be skipped):
          from: Pradipta
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Hi Suripa! Email has been triggered successfully,
          # Optional carbon copy recipients:
          cc: pradipta.chatterjee98@gmail.com
          # Optional blind carbon copy recipients:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
